Duncan.PEMS.Web/Areas/admin/Controllers/EventCodesUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using Duncan.PEMS.Business.Events;
using Duncan.PEMS.Entities.Events;
using Duncan.PEMS.Framework.Controller;
using Duncan.PEMS.Utilities;
using NLog;

namespace Duncan.PEMS.Web.Areas.admin.Controllers
{
    public class EventCodesUploadController : PemsController
    {
        #region NLog Logger

        /// <summary>
        /// NLog logger instance.
        /// </summary>
        private static Logger _logger = LogManager.GetCurrentClassLogger();

        #endregion

        private const string SessionFilePath = "PemsEventCodesBulkUpdate";
        private const string SessionFileName = "PemsEventCodesBulkUpdateFile";


        public ActionResult Upload(int customerId)
        {
            EventCodesCustomerModel model = (new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetEventCodesCustomerModel(customerId);

            return View(model);
        }


        public ActionResult UploadSubmit(IEnumerable<HttpPostedFileBase> files, EventCodesCustomerModel model)
        {
            Session.Remove(SessionFilePath);
            Session.Remove(SessionFileName);

            foreach (var file in files)
            {
                // Some browsers send file names with full path. We only care about the file name.
                var uniqueFileName = Guid.NewGuid().ToString() + ".csv";
                var destinationPath = Path.Combine(Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["pems.eventcodes.upload"]), uniqueFileName);

                file.SaveAs(destinationPath);

                Session[SessionFilePath] = destinationPath;
                Session[SessionFileName] = Path.GetFileName(file.FileName);
            }

            return RedirectToAction("UploadProcess", new { customerId = model.CustomerId });
        }



        public ActionResult UploadProcess(int customerId)
        {
            EventCodesUploadResultsModel model;

            var eventCodesFile = Session[SessionFilePath] as string;
            var fileName = Session[SessionFileName] as string;

            if (string.IsNullOrEmpty(eventCodesFile))
            {
                model = new EventCodesUploadResultsModel
                    {
                    CustomerId = customerId
                };
                model.Errors.Add("Unable to process uploaded file");
            }
            else
            {
                // Process the file.
                model = (new UploadFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).Process(customerId, eventCodesFile);

                // Note name of file in Results log.
                model.Results.Insert(0, "File Processed: " + fileName);

                // Clear the session variable.
                Session.Remove(SessionFilePath);
                Session.Remove(SessionFileName);

                // Delete the file.
                System.IO.File.Delete(eventCodesFile);

            }
            return View(model);
        }

        public FileResult DownloadExample(int customerId)
        {
            const string fileName = "eventcodes.csv";
            var fullFilePath = Path.Combine(Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["pems.eventcodes.samples"]), fileName);
            return File(fullFilePath, "text/csv", fileName);
        }

        public FileResult DownloadInstructions(int customerId)
        {
            // Make a copy of the appropriate instrunction template file.
            const string fileName = "eventcodes.txt";
            var sourcePath = Path.Combine(Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["pems.eventcodes.samples"]), fileName);

            var uniqueFileName = Guid.NewGuid().ToString() + ".txt";
            var destinationPath = Path.Combine(Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["pems.eventcodes.upload"]), uniqueFileName);

            System.IO.File.Copy(sourcePath, destinationPath, true);

            // Open the new file
            using (StreamWriter sw = System.IO.File.AppendText(destinationPath))
            {
                // Append the date to it.
                sw.WriteLine();
                sw.WriteLine("Created: " + DateTime.Now.ToShortDateString());
                sw.WriteLine();

                // Add appropriate constraints.
                var uploadFactory = new UploadFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString());

                sw.WriteLine(uploadFactory.ConstraintsList(customerId));
                sw.WriteLine();

                // Add appropriate field notes
                sw.WriteLine();
                sw.WriteLine(uploadFactory.FieldsList(customerId));

                // Save file.
                sw.Close();
            }


            return File(destinationPath, "text/txt", fileName);
        }



    }
}

Duncan.PEMS.Web/Areas/admin/Views/EventCodesUpload/Upload.cshtml
@model Duncan.PEMS.Entities.Events.EventCodesCustomerModel
@using Duncan.PEMS.Utilities
@using Kendo.Mvc.UI

@{
    ViewBag.Title = "Event Codes Upload";
}


@section PageHeader 
{
    <h1><a href="/">@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Home" )</a> / <a href="Index">@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Event Codes Management" )</a> / @HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Event Codes Upload" ) / <span>@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Upload Event Codes" )</span></h1>
}

    @using (Html.BeginForm("UploadSubmit", "EventCodesUpload", FormMethod.Post))
    {
        
        @Html.HiddenFor( m => m.CustomerId )
        
        <div class="clear">

            <div class="two-column payment">
                <div class="customer_tab_content_section">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Customer" )</div>
                <div class="clear" style="padding-top: 5px; padding-bottom: 5px">
                    @Html.DisplayFor( m => m.CustomerDisplayName, new {@class = "customer_text"} )
                </div>
                <div class="customer_tab_content_section">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Codes File to Upload" )</div>
                <div class="clear">
                    @(Html.Kendo().Upload()
                          .Name("files")
                          .Events(events => events
                                                .Progress("onProgress")
                                                .Select("onSelect")
                          )
                          )
                </div>
            </div>

            <div class="two-column payment">
                <div class="customer_tab_content_section">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Example Files" )</div>
                To download an example file or instructions, click on the appropriate links below.
                <div style="width: 95%">
                    <div style="float: left; padding-left: 80px">
                        @Html.ActionLink("Example", "DownloadExample", "EventCodesUpload", new { customerId = Model.CustomerId }, null)
                    </div>
                    <div style="float: right; padding-right: 60px">
                        @Html.ActionLink("Instructions", "DownloadInstructions", "EventCodesUpload", new { customerId = Model.CustomerId }, null)
                    </div>
                </div>
                <div style="float: right; width: 5%"></div>
            </div>
        </div>
        
        
        <div class="customer_actions">
            <button type="submit" name="submitButton" class="button" value="SAVE" >@HttpContext.Current.GetLocaleResource(ResourceTypes.Button, "Upload")</button>
                @Html.ActionLink( @HttpContext.Current.GetLocaleResource( ResourceTypes.Button, "Return" ).ToString(), "EditEventCodes", "Customers",
                                  new {customerId = Model.CustomerId}, new {@class = "button previous", @type = "button"} )
        </div>
    }





<script>
    
    function onSelect(e) {

        if (e.files.length > 1) {
            pemsPopupShowErrorWithTag(
    '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentArea]',
                '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentController]',
                '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentAction]',
"1236", "Only one file may be selected.");
            e.preventDefault();
        }
    }

    function onComplete(e) {
        alert("Done.");
    }

    function onProgress(e) {
        //kendoConsole.log("Upload progress :: " + e.percentComplete + "% :: " + getFileInfo(e));
    }



</script>

Duncan.PEMS.Web/Areas/admin/Views/EventCodesUpload/UploadProcess.cshtml
@model Duncan.PEMS.Entities.Events.EventCodesUploadResultsModel
@using Duncan.PEMS.Utilities
@using Kendo.Mvc.UI

@{
    ViewBag.Title = "Event Codes Upload Results";
}


@section PageHeader 
{
    <h1><a href="/">@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Home" )</a> / <a href="Index">@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Event Codes Management" )</a> / @HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Event Codes Upload" ) / <span>@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Upload Event Codes Results" )</span></h1>
}

            @(Html.Kendo().Grid(Model.Results)
              .Name("BulkSettingResultsLogGrid")
              .HtmlAttributes( new {style = "max-width: 1693px; height: 170px;"} )
              .Columns(columns =>
              {
                  columns.Bound("").Title("Log").HtmlAttributes(new { style = "text-align:left" }).HeaderHtmlAttributes(new { style = "text-align:left" });
              })
              .Pageable()
              .Scrollable()
            )
            @(Html.Kendo().Grid(Model.Errors)
              .Name("BulkSettingResultsErrorGrid")
              .HtmlAttributes( new {style = "max-width: 1693px; height: 300px;"} )
              .Columns(columns =>
              {
                  columns.Bound("").Title("Errors").HtmlAttributes(new { style = "text-align:left" }).HeaderHtmlAttributes(new { style = "text-align:left" });
              })
              .Pageable()
              .Scrollable()
            )
        
<div class="customer_actions">
            @Html.ActionLink( (string) ( HttpContext.Current.GetLocaleResource( ResourceTypes.Button, "Return" ) ?? "Return" ), "Upload", "EventCodesUpload",
                              new {customerId = Model.CustomerId}, new {@class = "button previous"} )
</div>





<script>
    
    function onSelect(e) {

        var grid = $("#BulkSettingResultsLogGrid");
        
        if (grid != null) {
            grid.empty();
            grid.kendoGrid();
        }

        grid = $("#BulkSettingResultsErrorGrid");

        if (grid != null) {
            grid.empty();
            grid.kendoGrid();
        }



        if (e.files.length > 1) {
            pemsPopupShowErrorWithTag(
    '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentArea]',
                '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentController]',
                '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentAction]',
"1234", "Only one file may be selected.");
            e.preventDefault();
        }
    }

    function onComplete(e) {
        alert("Done.");
    }

    function onProgress(e) {
        //kendoConsole.log("Upload progress :: " + e.percentComplete + "% :: " + getFileInfo(e));
    }



</script>