Duncan.PEMS.Web/Areas/admin/Controllers/EventCodesController.cs
/******************* CHANGE LOG ***********************************************************************************************************************
 * DATE                 NAME                   DESCRIPTION
 * ___________      ___________________        _________________________________________________________________________________________________________
 * 
 * 02/10/2014       Sergey Ostrerov            DPTXPEMS-237 - Edit Screen for Event Code Crashes
 *                                                            Create/Update Event Code   
 * 
 * *****************************************************************************************************************************************************/
using System.Web.Mvc;
using Duncan.PEMS.Business.Events;
using Duncan.PEMS.Entities.Events;
using Duncan.PEMS.Framework.Controller;
using Duncan.PEMS.Utilities;
using NLog;

namespace Duncan.PEMS.Web.Areas.admin.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class EventCodesController : PemsController
    {
        #region NLog Logger

        /// <summary>
        /// NLog logger instance.
        /// </summary>
        private static Logger _logger = LogManager.GetCurrentClassLogger();

        #endregion

        #region Create Event Code

        public ActionResult Details(int customerId, int eventSourceId, int eventCodeId)
        {
            var model = (new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetEventCodeViewModel(customerId, eventSourceId, eventCodeId);

            return View(model);
        }

        #endregion

        #region Create Event Code

        public ActionResult Create(int customerId)
        {
            var model = (new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetEventCodeEditModel(customerId);

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(EventCodeEditModel model)
        {
            // Save values
            if (!ModelState.IsValid)
            {
                (new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).RefreshEventCodeEditModel(model);
                return View(model);
            }
            var eventCodesFactory = new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString());
            // Does the requested EventCode settings indicae an
            // EventCode that already exists?
            if ( eventCodesFactory.CanCreateEventCode( model ) )
            {
                ModelState.AddModelError("Exists", "Event Code with this same Event Source, Event Type, Event Category and Asset Type already exists.");
                (new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).RefreshEventCodeEditModel(model);
                return View(model);
            }
            (new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).CreateEventCode(model);
            return RedirectToAction("EditEventCodes", "Customers", new { customerId = model.CustomerId });
        }

        #endregion


        #region Edit Event Code 

        public ActionResult Edit(int customerId, int eventSourceId, int eventCodeId, bool fromDetailsPage = false)
        {
            var model = (new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetEventCodeEditModel(customerId, eventSourceId, eventCodeId);

            model.FromDetailsPage = fromDetailsPage;

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EventCodeEditModel model)
        {
            // Save values
            if (!ModelState.IsValid)
            {
                (new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).RefreshEventCodeEditModel(model);
                return View(model);
            }
            (new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).SetEventCodeEditModel(model);

            // Saved and stay on same page.
            if ( model.FromDetailsPage )
                return RedirectToAction("Details", new { customerId = model.CustomerId, eventSourceId = model.SourceId, eventCodeId = model.Id });
            return RedirectToAction("EditEventCodes", "Customers", new { customerId = model.CustomerId });
        }

        #endregion


        #region Ajax Support

        public ActionResult GetAssetTypeSLA(int customerId, int meterGroupId, int ? currSlaMinutes, int currAssetTypeID)
        {
            // Get the default SLA minutes of this asset type for this customer.  This can be 
            // found in [AssetType] table.
            if (meterGroupId == -1 && meterGroupId != currAssetTypeID)
            {
                return Json(new { DefaultSLA = (new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAssetTypeDefaultSLA(customerId, meterGroupId) });
            }
            else if (meterGroupId != -1 && meterGroupId != currAssetTypeID)
            {
                return Json(new { DefaultSLA = (new EventCodesFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAssetTypeDefaultSLA(customerId, meterGroupId) });
            }
            return Json(new { DefaultSLA = currSlaMinutes});
        }

        #endregion

    }
}

Duncan.PEMS.Web/Areas/admin/Views/EventCodes/Create.cshtml
@model Duncan.PEMS.Entities.Events.EventCodeEditModel
@using Duncan.PEMS.Entities.Customers
@using Duncan.PEMS.Utilities
@using Kendo.Mvc.UI

@{
    ViewBag.Title = HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Create Event Code" );
}


@section PageHeader 
{
    <h1><a href="/">@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Manage Customer" )</a> / @HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Event Configuration Inquiry" ) / <span>@HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Create Event Configuration" )</span></h1>
}

<div class="validationSum-container">@Html.ErrorOverview( ViewData.ModelState )</div>


@using (Html.BeginForm( "Create", "EventCodes", FormMethod.Post, new {@class = "customer-form", @id = "createEventCode"} ))
{
    @Html.HiddenFor( m => m.CustomerId )
    @Html.HiddenFor( m => m.AlarmTypeId )
    @Html.HiddenFor(m => m.ApplySLA)


        <div class="customer_tab_content_section">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Code Details" )</div>    
        
        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Customer Name" )@Html.Raw( ": " )</div>
            @Html.DisplayFor( m => m.CustomerDisplayName, new {@class = "customer_text"} )&nbsp;
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Code" )@Html.Raw( ": " )</div>
            @(Html.Kendo().NumericTextBox<int>().Name( "Id" ).Min( -1 ).Format("n0").Decimals(0).Value(Model.Id).HtmlAttributes(new { style = "width: 80px" })) Note: -1 will cause value to be auto-generated.
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Long Description" )@Html.Raw( ": " )</div>
            @Html.TextBoxFor( m => m.DescVerbose, new {@class = "customer_text"} )
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Abbreviated Description" )@Html.Raw( ": " )</div>
            @Html.TextBoxFor( m => m.DescAbbrev, new {@class = "customer_text"} )
            <span class="required_asterisk">*</span>
            @Html.ValidationMessageFor( m => m.DescAbbrev )
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Type" )@Html.Raw( ": " )</div>
            @Html.DropDownListFor( m => m.TypeId, new SelectList( Model.Type, "Value", "Text" ), new {@class = "customer_text"} )
            <span class="required_asterisk">*</span>
            @Html.ValidationMessageFor( m => m.Type )
        </div>    
        
        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Source" )@Html.Raw( ": " )</div>
            @Html.DropDownListFor( m => m.SourceId, new SelectList( Model.Source, "Value", "Text" ), new {@class = "customer_text"} )
            <span class="required_asterisk">*</span>
            @Html.ValidationMessageFor( m => m.Source )
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Category" )@Html.Raw( ": " )</div>
            @Html.DropDownListFor( m => m.CategoryId, new SelectList( Model.Category, "Value", "Text" ), new {@class = "customer_text"} )
            <span class="required_asterisk">*</span>
            @Html.ValidationMessageFor( m => m.Category )
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Asset Type" )@Html.Raw( ": " )</div>
            @Html.DropDownListFor( m => m.AssetTypeId, new SelectList( Model.AssetType, "Value", "Text" ), new {@class = "customer_text"} )
            <span class="required_asterisk">*</span>
            @Html.ValidationMessageFor( m => m.AssetType )
        </div>    

        <div id="DefaultSLADiv">
            <div>
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "SLA Duration" )@Html.Raw( ": " )</div>
                @(Html.Kendo().NumericTextBox<int>().Name( "SLAMinutes" ).Min( 0 ).Max( 1440 ).Format("n0").Decimals(0).Value( Model.SLAMinutes ).HtmlAttributes(new { style = "width: 80px" })) Minutes  
                <span class="required_asterisk">*</span>
                @Html.ValidationMessageFor( m => m.SLAMinutes )
            </div>    
        </div>    

        <div id="AlarmTierDiv">
            <div>
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Is Alarm" )@Html.Raw( ": " )</div>
                @Html.CheckBoxFor( m => m.IsAlarm, new {@class = "checkbox"} )
                <span class="required_asterisk">*</span>
                @Html.ValidationMessageFor( m => m.IsAlarm )
            </div>    
        </div>
        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Alarm Severity" )@Html.Raw( ": " )</div>
            @Html.DropDownListFor( m => m.AlarmTierId, new SelectList( Model.AlarmTier, "Value", "Text" ), new {@class = "customer_text"} )
            <span class="required_asterisk">*</span>
            @Html.ValidationMessageFor( m => m.AlarmTier )
        </div>    
    
        <div class="customer_actions">
            <button type="submit" name="submitButton" class="button important" value="SAVE">@HttpContext.Current.GetLocaleResource( ResourceTypes.Button, "Save" )</button>
            @if ( Model.FromDetailsPage )
            {
                @Html.ActionLink( @HttpContext.Current.GetLocaleResource( ResourceTypes.Button, "Return" ).ToString(), "Details", "EventCodes",
                                  new {customerId = Model.CustomerId, eventSourceId = Model.SourceId, eventCodeId = Model.Id},
                                  new {@class = "button previous", @type = "button"} )
            }
            else
            {
                @Html.ActionLink( @HttpContext.Current.GetLocaleResource( ResourceTypes.Button, "Return" ).ToString(), "EditEventCodes", "Customers",
                                  new {customerId = Model.CustomerId}, new {@class = "button previous", @type = "button"} )
            }
        </div>

}







<script type="text/javascript">
    var currAssetTypeID;
    $(document).ready(function() {
        currAssetTypeID =@Model.AssetTypeId
        $("#TypeId").change(OnTypeChanged);
        $("#AssetTypeId").change(OnAssetTypeChanged);
        

        // Show or hide AlarmTierDiv
        if ($("#TypeId").val() == "@Model.AlarmTypeId") {
            $("#AlarmTierDiv").show();
        } else {
            $("#AlarmTierDiv").hide();
        }
        
        // Hide/show SLA element
        OnActionGetDefaultSLA($("#AssetTypeId").val());
        
        $("#SLAMinutes").width(50);
    });

    function OnTypeChanged(data, textStatus, jqXHR) {

        if ($(this).val() == "@Model.AlarmTypeId") {
            $("#AlarmTierDiv").show();
        } else {
            $("#AlarmTierDiv").hide();
        }
    }

    function OnAssetTypeChanged(data, textStatus, jqXHR) {
        OnActionGetDefaultSLA($(this).val());
    }


    function OnActionGetDefaultSLA(meterGroupId) {
        var slaVal = 0;
        // Make AJAX call to get default SLA
        $.ajax({
            url: '@Url.Action( "GetAssetTypeSLA" )',
            data: { customerId: '@Model.CustomerId', meterGroupId: meterGroupId, currSlaMinutes: slaVal, currAssetTypeID: currAssetTypeID },
            type: 'POST',
            success: OnActionGetDefaultSLASuccess,
            error: function (data) {
                pemsPopupShowErrorWithTag(
    '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentArea]',
                '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentController]',
                '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentAction]',
"1234", data.responseText);
            },
        });
    }


    function OnActionGetDefaultSLASuccess(data, textStatus, jqXHR) {

        var defaultSLA = data.DefaultSLA;
        
        var numerictextbox = $("#SLAMinutes").data("kendoNumericTextBox");

        if (defaultSLA > 0) {
            $("#DefaultSLADiv").show();
            $('#ApplySLA').val(true);
            numerictextbox.value(defaultSLA);
        } else {
            $("#DefaultSLADiv").hide();
            $('#ApplySLA').val(false);
            numerictextbox.value("");
        }
    }

</script>

Duncan.PEMS.Web/Areas/admin/Views/EventCodes/Details.cshtml
@model Duncan.PEMS.Entities.Events.EventCodeViewModel
@using Duncan.PEMS.Entities.Customers
@using Duncan.PEMS.Utilities
@using Kendo.Mvc.UI

@{
    ViewBag.Title = HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "View Event Code" );
}


@section PageHeader 
{
    <h1><a href="/">@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Manage Customer" )</a> / @HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Event Configuration Inquiry" ) / <span>@HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Event" )</span></h1>
}


    <div class="customer_tab_content">
    
        <div class="customer_tab_content_section">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Code Details" )</div>    
        
        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Customer Name" )@Html.Raw( ": " )</div>
            @Html.DisplayFor( m => m.CustomerDisplayName, new {@class = "customer_text"} )&nbsp;
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Code" )@Html.Raw( ": " )</div>
            @Html.DisplayFor( m => m.Id, new {@class = "customer_text"} )&nbsp;
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Long Description" )@Html.Raw( ": " )</div>
            @Html.DisplayFor( m => m.DescVerbose, new {@class = "customer_text"} )&nbsp;
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Abreviated Description" )@Html.Raw( ": " )</div>
            @Html.DisplayFor(m => m.DescAbbrev, new {@class = "customer_text"} ) &nbsp;
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Type" )@Html.Raw( ": " )</div>
            @Html.DisplayFor( m => m.Type, new {@class = "customer_text"} )&nbsp;
        </div>    
        
        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Source" )@Html.Raw( ": " )</div>
            @Html.DisplayFor( m => m.Source, new {@class = "customer_text"} )&nbsp;
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Category" )@Html.Raw( ": " )</div>
            @Html.DisplayFor( m => m.Category, new {@class = "customer_text"} )&nbsp;
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Asset Type" )@Html.Raw( ": " )</div>
            @Html.DisplayFor( m => m.AssetType, new {@class = "customer_text"} )&nbsp;
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "SLA Duration" )@Html.Raw( ": " )</div>
            @if ( Model.SLAMinutes > -1 )
            {
                Html.DisplayFor( m => m.SLAMinutes, new {@class = "customer_text"} );
            }
            &nbsp;
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Is Alarm" )@Html.Raw( ": " )</div>
            @Html.CheckBoxFor( m => m.IsAlarm, new {@class = "checkbox", disabled="disabled"} )
        </div>    
    
        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Alarm Severity" )@Html.Raw( ": " )</div>
            @Html.DisplayFor(m => m.AlarmTier, new {@class = "customer_text"} ) &nbsp;
        </div>    

    
        <div class="customer_actions">
            @Html.ActionLink(@HttpContext.Current.GetLocaleResource(ResourceTypes.Button, "Update").ToString(), "Edit", "EventCodes", 
                new {customerId = Model.CustomerId, eventSourceId = Model.SourceId, eventCodeId = Model.Id, fromDetailsPage = true}, new { @class = "button important", @type = "button" })
            @Html.ActionLink( @HttpContext.Current.GetLocaleResource( ResourceTypes.Button, "Return" ).ToString(), "EditEventCodes", "Customers",
                new {customerId = Model.CustomerId}, new {@class = "button previous", @type = "button"} )
        </div>

    </div>

Duncan.PEMS.Web/Areas/admin/Views/EventCodes/Edit.cshtml
@* /******************* CHANGE LOG ***********************************************************************************************************************
 * DATE                 NAME                       DESCRIPTION
 * ___________          ___________________        _______________________________________________________________________________________________
 * 
 * 02/14/2014           Sergey Ostrerov            DPTXPEMS-237 - Edit Screen for Event Code Crashes. Edit Event Code: SLA Duration is not updated.
 * 
 * *****************************************************************************************************************************************************/ *@

@model Duncan.PEMS.Entities.Events.EventCodeEditModel
@using Duncan.PEMS.Entities.Customers
@using Duncan.PEMS.Utilities
@using Kendo.Mvc.UI

@{
    ViewBag.Title = HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Update Event Code" );
}


@section PageHeader 
{
    <h1><a href="/">@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Manage Customer" )</a> / @HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Event Configuration Inquiry" ) / <span>@HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Update Event Configuration" )</span></h1>
}

<div class="validationSum-container">@Html.ErrorOverview( ViewData.ModelState )</div>


@using (Html.BeginForm( "Edit", "EventCodes", FormMethod.Post, new {@class = "customer-form", @id = "editEventCode"} ))
{
    @Html.HiddenFor( m => m.CustomerId )
    @Html.HiddenFor( m => m.AlarmTypeId )
    @Html.HiddenFor(m => m.ApplySLA)


        <div class="customer_tab_content_section">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Code Details" )</div>    
        
        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Customer Name" )@Html.Raw( ": " )</div>
            @Html.DisplayFor( m => m.CustomerDisplayName, new {@class = "customer_text"} )&nbsp;
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Code" )@Html.Raw( ": " )</div>
            @Html.DisplayFor( m => m.Id, new {@class = "customer_text"} )&nbsp;
            @Html.HiddenFor( m => m.Id )
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Long Description" )@Html.Raw( ": " )</div>
            @Html.TextBoxFor( m => m.DescVerbose, new {@class = "customer_text"} )
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Abbreviated Description" )@Html.Raw( ": " )</div>
            @Html.TextBoxFor( m => m.DescAbbrev, new {@class = "customer_text"} )
            <span class="required_asterisk">*</span>
            @Html.ValidationMessageFor( m => m.DescAbbrev )
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Type" )@Html.Raw( ": " )</div>
            @Html.DropDownListFor( m => m.TypeId, new SelectList( Model.Type, "Value", "Text" ), new {@class = "customer_text"} )
            <span class="required_asterisk">*</span>
            @Html.ValidationMessageFor( m => m.Type )
        </div>    
        
        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Source" )@Html.Raw( ": " )</div>
            @Html.DisplayFor( m => m.SourceDisplay, new {@class = "customer_text"} )&nbsp;
            @Html.HiddenFor( m => m.SourceDisplay )
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Category" )@Html.Raw( ": " )</div>
            @Html.DropDownListFor( m => m.CategoryId, new SelectList( Model.Category, "Value", "Text" ), new {@class = "customer_text"} )
            <span class="required_asterisk">*</span>
            @Html.ValidationMessageFor( m => m.Category )
        </div>    

        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Asset Type" )@Html.Raw( ": " )</div>
            @Html.DropDownListFor( m => m.AssetTypeId, new SelectList( Model.AssetType, "Value", "Text" ), new {@class = "customer_text"} )
            <span class="required_asterisk">*</span>
            @Html.ValidationMessageFor( m => m.AssetType )
        </div>    

        <div id="DefaultSLADiv">
            <div>
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "SLA Duration" )@Html.Raw( ": " )</div>
                @(Html.Kendo().NumericTextBox<int>().Name( "SLAMinutes" ).Min( 0 ).Max( 1440 ).Format("n0").Decimals(0).Value( Model.SLAMinutes ).HtmlAttributes(new { style = "width: 80px" })) Minutes  
                <span class="required_asterisk">*</span>
                @Html.ValidationMessageFor( m => m.SLAMinutes )
            </div>    
        </div>    

        <div id="AlarmTierDiv">
            <div>
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Is Alarm" )@Html.Raw( ": " )</div>
                @Html.CheckBoxFor( m => m.IsAlarm, new {@class = "checkbox"} )
                <span class="required_asterisk">*</span>
                @Html.ValidationMessageFor( m => m.IsAlarm )
            </div>    
        </div>
        <div>
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Alarm Severity" )@Html.Raw( ": " )</div>
            @Html.DropDownListFor( m => m.AlarmTierId, new SelectList( Model.AlarmTier, "Value", "Text" ), new {@class = "customer_text"} )
            <span class="required_asterisk">*</span>
            @Html.ValidationMessageFor( m => m.AlarmTier )
        </div>    
    
        <div class="customer_actions">
            <button type="submit" name="submitButton" class="button important" value="SAVE">@HttpContext.Current.GetLocaleResource( ResourceTypes.Button, "Save" )</button>
            @if ( Model.FromDetailsPage )
            {
                @Html.ActionLink( @HttpContext.Current.GetLocaleResource( ResourceTypes.Button, "Return" ).ToString(), "Details", "EventCodes",
                                  new {customerId = Model.CustomerId, eventSourceId = Model.SourceId, eventCodeId = Model.Id},
                                  new {@class = "button previous", @type = "button"} )
            }
            else
            {
                @Html.ActionLink( @HttpContext.Current.GetLocaleResource( ResourceTypes.Button, "Return" ).ToString(), "EditEventCodes", "Customers",
                                  new {customerId = Model.CustomerId}, new {@class = "button previous", @type = "button"} )
            }
        </div>

}







<script type="text/javascript">
    var currAssetTypeID;
    $(document).ready(function() {
        currAssetTypeID =@Model.AssetTypeId
        $("#TypeId").change(OnTypeChanged);
        $("#AssetTypeId").change(OnAssetTypeChanged);
        

        // Show or hide AlarmTierDiv
        if ($("#TypeId").val() == "@Model.AlarmTypeId") {
            $("#AlarmTierDiv").show();
        } else {
            $("#AlarmTierDiv").hide();
        }
        
        // Hide/show SLA element
        OnActionGetDefaultSLA($("#AssetTypeId").val());
        
        $("#SLAMinutes").width(50);
    });

    function OnTypeChanged(data, textStatus, jqXHR) {

        if ($(this).val() == "@Model.AlarmTypeId") {
            $("#AlarmTierDiv").show();
        } else {
            $("#AlarmTierDiv").hide();
        }
    }

    function OnAssetTypeChanged(data, textStatus, jqXHR) {
        OnActionGetDefaultSLA($(this).val());
    }


    function OnActionGetDefaultSLA(meterGroupId) {
        var slaVal = @Model.SLAMinutes
        // Make AJAX call to get default SLA
        $.ajax({
            url: '@Url.Action( "GetAssetTypeSLA" )',
            data: { customerId: '@Model.CustomerId', meterGroupId: meterGroupId, currSlaMinutes: slaVal, currAssetTypeID: currAssetTypeID },
            type: 'POST',
            success: OnActionGetDefaultSLASuccess,
            error: function (data) {
                pemsPopupShowErrorWithTag(
    '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentArea]',
                '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentController]',
                '@ViewData[Duncan.PEMS.Utilities.Constants.ViewData.CurrentAction]',
                "1234", data.responseText);
            },
        });
    }


    function OnActionGetDefaultSLASuccess(data, textStatus, jqXHR) {

        var defaultSLA = data.DefaultSLA;
        
        var numerictextbox = $("#SLAMinutes").data("kendoNumericTextBox");

        if (defaultSLA > 0) {
            $("#DefaultSLADiv").show();
            $('#ApplySLA').val(true);
            numerictextbox.value(defaultSLA);
        } else {
            $("#DefaultSLADiv").hide();
            $('#ApplySLA').val(false);
            numerictextbox.value("");
        }
    }

</script>