Duncan.PEMS.Web/Areas/city/Controllers/AlarmsController.cs
/******************* CHANGE LOG ***********************************************************************************************************************
 * DATE                 NAME                   DESCRIPTION
 * ___________      ___________________        _________________________________________________________________________________________________________
 * 
 * 01/23//2014      Sergey Ostrerov            DPTXPEMS-107 - PEMS: Alarm Inquiry >PDF export file has 2 rows in the header.
 * 
 * *****************************************************************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Duncan.PEMS.Business.Alarms;
using Duncan.PEMS.Business.Exports;
using Duncan.PEMS.Entities.Alarms;
using Duncan.PEMS.Framework.Controller;
using Duncan.PEMS.Utilities;
using Kendo.Mvc;
using Kendo.Mvc.UI;
using NLog;

namespace Duncan.PEMS.Web.Areas.city.Controllers
{
     [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
    public class AlarmsController : PemsController
    {
        #region NLog Logger

        /// <summary>
        /// NLog logger instance.
        /// </summary>
        private static Logger _logger = LogManager.GetCurrentClassLogger();

        #endregion

        #region "Listing"
        
        public ActionResult Index()
        {
            ViewBag.CurrentCityID = CurrentCity.Id;
            return View();
        }

        [HttpGet]
        public ActionResult GetItems([DataSourceRequest] DataSourceRequest request)
        {
            //now save the sort filters
            if (request.Sorts.Count > 0)
                SetSavedSortValues(request.Sorts, "Alarm");

            //get models
            var items = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAlarms(request, "TimeOfOccurrance desc");

            int total = 0;
            if (items.Any())
            {
                total = items.First().Count;

                //additional requirement, if the time til > 0, just set it as 0. we are going to do it here and NOT in the view

                foreach (var spAlarmModel in items)
                {
                    if (spAlarmModel.TotalMinutes < 0)
                        spAlarmModel.TotalMinutes = 0;

                    spAlarmModel.TotalMinutesDisplay = FormatHelper.FormatTimeFromMinutes(spAlarmModel.TimeRemainingUntilTarget, (int)PEMSEnums.PEMSEnumsTimeFormats.timeFormat_HHH_MM);
                }


            }
            DataSourceResult result = new DataSourceResult()  //** Sairam made changes on dec 17th 2014
            //var result = new DataSourceResult
            {
                Data = items,
                Total = total,
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region "Filter Values"

        public JsonResult GetAssetTypes( int cityId )
        {
            var assetTypes = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAlarmAssetTypes(cityId);
            return Json( assetTypes, JsonRequestBehavior.AllowGet ); 
        }

        /// <summary>
        /// Gets the list items in the AlarmStatus dropdown list
        /// </summary>
        /// <returns></returns>
        public JsonResult GetAlarmStatuses()
        {
            var values = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAlarmStatusValues();

            return Json(values, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Gets the list items in the AlarmStatus dropdown list
        /// </summary>
        /// <returns></returns>
        public JsonResult GetTargetServices(int cityId)
        {
            var values = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetTargetServices(cityId);
            return Json(values, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Gets a list of items for the Asset State dropdown filter
        /// </summary>
        /// <returns><see cref="JsonResult"/> formatted list of asset statuses </returns>
        public JsonResult GetAssetStates()
        {
            var assets = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAssetStates();
            return Json(assets, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Gets a list of items for the Event Sources filter
        /// </summary>
        /// <returns><see cref="JsonResult"/> formatted list of alarm sources </returns>
        public JsonResult GetAlarmSources()
        {
            var sources = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAlarmSources();
            return Json(sources, JsonRequestBehavior.AllowGet);
        }
        
        /// <summary>
        /// Gets a list of items in the TimeTypes dropdown list
        /// </summary>
        /// <returns><see cref="JsonResult"/> formatted list of time types </returns>
        public JsonResult GetTimeTypes()
        {
            var timeTypes = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAlarmTimeTypes();
            return Json(timeTypes, JsonRequestBehavior.AllowGet); 
        }

        /// <summary>
        /// Gets a JSON-formatted list of alarm severities.
        /// </summary>
        /// <returns><see cref="JsonResult"/> formatted list of alarm severities </returns>
        public JsonResult GetAlarmSeverities()
        {
            var severities = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAlarmServities();
            return Json(severities, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Gets a list of Technicians for the TechnicianID dropdown
        /// </summary>
        /// <returns></returns>
        public JsonResult GetTechnicianDetails()
        {
            var techs = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAlarmTechnicians();
            return Json(techs, JsonRequestBehavior.AllowGet);
        }



        /// <summary>
        /// Gets a list of items for the Alarm filter
        /// </summary>
        /// <returns></returns>
        public JsonResult GetAlarmFilters(int customerId)
        {
            var items = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAlarmFilters(customerId);
            return Json(items, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Gets a list of Areas for the Areas filter
        /// </summary>
        /// <returns></returns>
        public JsonResult GetAlarmAreas(int cityId)
        {
            var areas = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAlarmAreas(cityId);
            return Json(areas, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Gets a list of items for the Zones filter
        /// </summary>
        /// <returns></returns>
        public JsonResult GetAlarmZones(int cityId)
        {
            var zones = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAlarmZones(cityId);
            return Json(zones, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Gets a list of items for the Suburbs dropdown list
        /// </summary>
        /// <returns></returns>
        public JsonResult GetAlarmSubAreas(int cityId)
        {
            var areas = (new AlarmFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString())).GetAlarmSubAreas(cityId);
            return Json(areas, JsonRequestBehavior.AllowGet);
        }


        #endregion

        #region "Exporting"

        public FileResult ExportToCsv([DataSourceRequest]DataSourceRequest request)
        {
            var items = GetExportData(request);
            var output = (new ExportFactory()).GetCsvFileMemoryStream(items, CurrentController, "GetItems", CurrentCity.Id);
            return File(output, "text/comma-separated-values", "AlarmsExport_" + FormatHelper.FormatDateTime(DateTime.Now) + ".csv");
        }

        public FileResult ExportToExcel([DataSourceRequest]DataSourceRequest request, string customerId, string startDate, string endDate, string timeType)
        {
            var items = GetExportData(request);
            var filters = new List<FilterDescriptor>();
            //pass in an empty list
            filters = GetFilterDescriptors(request.Filters, filters);

            var itemToRemove = filters.FirstOrDefault(r => r.Member == "CustomerId");
            if (itemToRemove != null) filters.Remove(itemToRemove);
            var output = (new ExportFactory()).GetExcelFileMemoryStream(items, CurrentController, "GetItems", CurrentCity.Id, filters);
            return File(output.ToArray(),   //The binary data of the XLS file
              "application/vnd.ms-excel", //MIME type of Excel files
              "AlarmsExport_" + FormatHelper.FormatDateTime(DateTime.Now) + ".xls");     //Suggested file name in the "Save as" dialog which will be displayed to the end user
        }

        public FileResult ExportToPdf([DataSourceRequest]DataSourceRequest request, string customerId, string startDate, string endDate, string timeType)
        {
            var items = GetExportData(request);
            var filters = new List<FilterDescriptor>();
            //pass in an empty list
            filters = GetFilterDescriptors(request.Filters, filters);

Duncan.PEMS.Web/Areas/city/Views/Events/Details.cshtml
@using Duncan.PEMS.Utilities
@model Duncan.PEMS.Entities.Events.EventDetails

@{
    ViewBag.Title = HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Event Details" );
}

@section PageHeader 
{
    <h1><a href="/">@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Home" )</a> / <a href="Index">@HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Event Management" )</a> / <span>@HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Event Details" )</span></h1>
}

<div class="grid cf">
    <div class="validation-summary-valid">
        @Html.ValidationSummary()
    </div>
    
    @if ( Model != null )
    {
        <div class="customer_tab_content_section">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Asset / Location" )</div>
        <div class="two-column">
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Asset Id" ):</div>
                <div class="customer_text">@Model.AssetId</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Asset Name" ):</div>
                <div class="customer_text">@Model.AssetName</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Area" ):</div>
                <div class="customer_text">@Model.Area</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Zone" ):</div>
                <div class="customer_text">@Model.Zone</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Suburb" ):</div>
                <div class="customer_text">@Model.Suburb</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Street" ):</div>
                <div class="customer_text">@Model.Street</div>
            </div>
        </div>
        <div class="two-column">
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Asset Type" ):</div>
                <div class="customer_text">@Model.AssetType</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Latitude" ):</div>
                @Html.DisplayForLatLong( m => m.Latitude, new {@class = "customer_text"} )
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Longitude" ):</div>
                @Html.DisplayForLatLong( m => m.Longitude, new {@class = "customer_text"} )
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Demand Area" ):@Html.Tooltip( "DemandArea" )</div>
                <div class="customer_text">@Model.DemandArea</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Bays Affected" ):@Html.Tooltip( "BaysAffected" )</div>
                <div class="customer_text">@Model.BaysAffected </div>
            </div>
        </div>

        <div class="customer_tab_content_section">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Information" ):</div>
        <div class="two-column">
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Id" ):</div>
                <div class="customer_text">@Model.EventId</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Code" ):</div>
                <div class="customer_text">@Model.EventCode</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Source" ):@Html.Tooltip( "EventSource" )</div>
                <div class="customer_text">@Model.EventSourceDescription </div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Technician Id" ):</div>
                <div class="customer_text">@Model.TechnicianId</div>
            </div>
        </div>
        <div class="two-column">
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Event Date / Time" ):</div>
                <div class="customer_text">@Model.EventDateTime.ToString( "g" )</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Day of Week" ):</div>
                <div class="customer_text">@Model.EventDateTime.DayOfWeek</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Peak" ):@Html.Tooltip( "Peak" )</div>
                <div class="customer_text">@FormatHelper.FormatBoolean( Model.Peak )</div>
            </div>
            @*            @if ( Model.TimeTypes != null && Model.TimeTypes.Any() )
            {
                <div class="detailRow">
                    <div class="customer_text_label"><span style="text-decoration: underline">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Time Tier" )</span>@Html.Tooltip( "TimeTier" )</div><br/>
                    @{
                        IEnumerable<string> timeTypes = from x in Model.TimeTypes select x.Description;
                        string csv = String.Join( ", ", timeTypes );
                    }
                    <div class="customer_text_label">@Html.Raw( csv )</div>
                </div>
            }*@
        </div>

        <div class="clear">
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Abbreviated Description" )</div>
                <div class="customer_text long_text">@Model.AbbrDesc</div>
            </div>
            <div class="detailRow">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Long Description" ) </div>
                <div class="customer_text long_text">@Model.LongDesc</div>
            </div>
        </div>
    }
    
    <div class="customer_actions">
        @Html.ActionLink( HttpContext.Current.GetLocaleResource( ResourceTypes.Label, "Return" ).ToString(), "Index", new {rtn = "true"}, new {@class = "button previous"} )
    </div>
</div>

Duncan.PEMS.Web/Areas/city/Views/Events/_AlarmsGrid.cshtml
@* /******************* CHANGE LOG ***********************************************************************************************************************
 * DATE                 NAME                        DESCRIPTION
 * ___________          ___________________        _______________________________________________________________________________________________
 * 
 * 01/23/2014           Sergey Ostrerov            DPTXPEMS-74 - AssetId isn't available in grid page although it's available in filter
 * 
 * *****************************************************************************************************************************************************/ *@

@using Kendo.Mvc.UI
@model IEnumerable<Duncan.PEMS.Entities.Events.AlarmsEventModel>

@(Html.Kendo().Grid( Model )
      .HtmlAttributes( new {style = "max-width: 1693px; height: 470px;"} )
      .Name( "CurrentGrid" )
      .Columns( columns =>
                    {
                        columns.Bound(p => p.DateTime).ClientTemplate("#= DateTimeDisplay #").Width(175);
                        columns.Bound( p => p.EventUID ).ClientTemplate( @Html.ActionLink( "#= EventUID #", "AlarmDetails", "Alarms", new
                                                                                                                                          {
                                                                                                                                              eventId = "#= EventUID #",
                                                                                                                                              isClosed = "#= IsClosed #",
                                                                                                                                              customerId = "#= CustomerID #"
                                                                                                                                          },
                                                                                           new {@onclick = "OnRowSelected(this);"} ).ToHtmlString() ).Width( 100 );
                        columns.Bound( p => p.AssetType ).Width( 150 );
                        columns.Bound(p => p.AssetId).Width(150);
                        columns.Bound( p => p.AssetName ).Width( 175 );
                        columns.Bound(p => p.TimeNotified).ClientTemplate("#= TimeNotifiedDisplay #").Width(175);
                        columns.Bound(p => p.TimeCleared).ClientTemplate("#= TimeClearedDisplay #").Width(175);
                        columns.Bound(p => p.TimeDueSLA).ClientTemplate("#= TimeDueSLADisplay #").Width(125);
                        columns.Bound( p => p.AlarmDescription ).Width( 175 );
                        columns.Bound( p => p.Source ).Width( 100 );
                        columns.Bound( p => p.AlarmSeverity ).Width( 125 );
                        columns.Bound( p => p.WorkOrderId ).Width( 125 );
                        columns.Bound( p => p.ResolutionCode ).Width( 125 );
                        columns.Bound( p => p.Technician ).Width( 150 );
                    } )
      .Selectable( select => select.Mode( GridSelectionMode.Single ).Type( GridSelectionType.Row ) )
      .Reorderable( reorder => reorder.Columns( false ) )
      .Pageable( pager => pager.PageSizes( true ).PageSizes( new int[] {100, 250, 500, 1000} ) )
      .AutoBind( false )
      .Sortable( sortable => sortable.SortMode( GridSortMode.MultipleColumn ) )
      .Resizable( resize => resize.Columns( true ) )
      .Scrollable()
      .Events( events => events.DataBound( "OnGridDataBound" ) )
      .Events( events => events.Change( "OnRowSelected" ) )
      .Events( events => events.ColumnResize( "OnRowResized" ) )
      .DataSource( dataSource => dataSource.Ajax().Read( read => read.Action( "GetAlarmEvents", "Events" ).Data( "additionalData" ) )
      ))

Duncan.PEMS.Web/Areas/city/Views/Events/_CollectionCBRGrid.cshtml
@* /******************* CHANGE LOG ***********************************************************************************************************************
 * DATE                 NAME                        DESCRIPTION
 * ___________          ___________________        _______________________________________________________________________________________________
 * 
 * 01/23/2014           Sergey Ostrerov            DPTXPEMS-74 - AssetId isn't available in grid page although it's available in filter
 * 
 * *****************************************************************************************************************************************************/ *@

@using Kendo.Mvc.UI
@model IEnumerable<Duncan.PEMS.Entities.Events.CollectionCBREventModel>

@(Html.Kendo().Grid( Model )
      .Name( "CurrentGrid" )
      .HtmlAttributes( new {style = "max-width: 1693px; height: 470px;"} )
      .Columns( columns =>
                    {
                        columns.Bound(p => p.DateTime).ClientTemplate("#= DateTimeDisplay #").Width(175);
                        columns.Bound( p => p.EventUID ).Width( 100 ).ClientTemplate( "#= CreateDetailLink(EventUID) #" );
                        columns.Bound(p => p.AssetId).Width(150);
                        columns.Bound( p => p.AssetName ).Width( 175 );
                        columns.Bound(p => p.RemovalTime).ClientTemplate("#= RemovalTimeDisplay #").Width(175);
                        columns.Bound(p => p.InsertionTime).ClientTemplate("#= InsertionTimeDisplay #").Width(175);
                        columns.Bound(p => p.TimeActive).Width(125);
                        columns.Bound( p => p.CBID ).Width( 175 );
                        columns.Bound(p => p.SequenceNumber).Width(175);
                        columns.Bound(p => p.AmtAuto).Width(120);
                        columns.Bound(p => p.AmtManual).Width(120);
                        columns.Bound(p => p.AmtDifference).Width(120);
                        columns.Bound(p => p.OperatorId).Width(150);
                        columns.Bound(p => p.Version).Width(75);
                        columns.Bound( p => p.TransactionFileName ).Width( 400 );
                    } )
      .Selectable( select => select.Mode( GridSelectionMode.Single ).Type( GridSelectionType.Row ) )
      .Reorderable( reorder => reorder.Columns( false ) )
      .Pageable( pager => pager.PageSizes( true ).PageSizes( new int[] {100, 250, 500, 1000} ) )
      .AutoBind( false )
      .Sortable( sortable => sortable.SortMode( GridSortMode.MultipleColumn ) )
      .Resizable( resize => resize.Columns( true ) )
      .Scrollable()
      .Events( events => events.DataBound( "OnGridDataBound" ) )
      .Events( events => events.Change( "OnRowSelected" ) )
      .Events( events => events.ColumnResize( "OnRowResized" ) )
      .Scrollable( scroll => scroll.Enabled( true ) )
      .DataSource( dataSource => dataSource.Ajax().Read( read => read.Action( "GetCollectionCBREvents", "Events" ).Data( "additionalData" ) )
      ))

Duncan.PEMS.Web/Areas/city/Views/Events/_CollectionCommGrid.cshtml
@* /******************* CHANGE LOG ***********************************************************************************************************************
 * DATE                 NAME                        DESCRIPTION
 * ___________          ___________________        _______________________________________________________________________________________________
 * 
 * 01/23/2014           Sergey Ostrerov            DPTXPEMS-74 - AssetId isn't available in grid page although it's available in filter
 * 
 * *****************************************************************************************************************************************************/ *@

@using Kendo.Mvc.UI
@model IEnumerable<Duncan.PEMS.Entities.Events.CollectionCommEventModel>

@(Html.Kendo().Grid( Model )
      .Name( "CurrentGrid" )
      .HtmlAttributes( new {style = "max-width: 1693px; height: 470px;"} )
      .Columns( columns =>
                    {
                        columns.Bound(p => p.DateTime).ClientTemplate("#= DateTimeDisplay #").Width(175);
                        columns.Bound( p => p.EventUID ).Width( 100 ).ClientTemplate( "#= CreateDetailLink(EventUID) #" );
                        columns.Bound(p => p.AssetId).Width(150);
                        columns.Bound(p => p.AssetName).Width(175);
                        columns.Bound(p => p.InsertionTime).ClientTemplate("#=InsertionTimeDisplay #").Width(175);
                        columns.Bound(p => p.Amount).ClientTemplate("#= AmountDisplay #").Width(125);
                        columns.Bound( p => p.PreviousCBID ).Width( 150 );
                        columns.Bound(p => p.NewCBID).Width(150);
                        columns.Bound(p => p.SequenceNumber).Width(130);
                    } )
      .Selectable( select => select.Mode( GridSelectionMode.Single ).Type( GridSelectionType.Row ) )
      .Reorderable( reorder => reorder.Columns( false ) )
      .Pageable( pager => pager.PageSizes( true ).PageSizes( new int[] {100, 250, 500, 1000} ) )
      .AutoBind( false )
      .Sortable( sortable => sortable.SortMode( GridSortMode.MultipleColumn ) )
      .Resizable( resize => resize.Columns( true ) )
      .Scrollable()
      .Events( events => events.DataBound( "OnGridDataBound" ) )
      .Events( events => events.Change( "OnRowSelected" ) )
      .Events( events => events.ColumnResize( "OnRowResized" ) )
      .DataSource( dataSource => dataSource.Ajax().Read( read => read.Action( "GetCollectionCommEvents", "Events" ).Data( "additionalData" ) )
      ))

Duncan.PEMS.Web/Areas/city/Views/Events/_ConnectionsGrid.cshtml
@* /******************* CHANGE LOG ***********************************************************************************************************************
 * DATE                 NAME                        DESCRIPTION
 * ___________          ___________________        _______________________________________________________________________________________________
 * 
 * 01/23/2014           Sergey Ostrerov            DPTXPEMS-74 - AssetId isn't available in grid page although it's available in filter
 * 
 * *****************************************************************************************************************************************************/ *@

@using Kendo.Mvc.UI
@model IEnumerable<Duncan.PEMS.Entities.Events.ConnectionEventModel>

@(Html.Kendo().Grid( Model )
      .Name( "CurrentGrid" )
      .HtmlAttributes( new {style = "max-width: 1693px; height: 470px;"} )
      .Columns( columns =>
                    {
                        columns.Bound(p => p.DateTime).ClientTemplate("#= DateTimeDisplay #").Width(175);
                        columns.Bound( p => p.EventUID ).Width( 100 ).ClientTemplate( "#= CreateDetailLink(EventUID) #" );
                        columns.Bound( p => p.AssetType ).Width( 150 );
                        columns.Bound(p => p.AssetId).Width(150);
                        columns.Bound( p => p.AssetName ).Width( 175 );
                        columns.Bound( p => p.ConnectionStatus ).Width( 150 );
                        columns.Bound( p => p.ErrorDescription ).Width( 150 );
                        columns.Bound(p => p.EndTime).ClientTemplate("#= EndTimeDisplay #").Width(175);
                        columns.Bound( p => p.Period ).Width( 100 );
                        columns.Bound( p => p.Port ).Width( 75 );
                    } )
      .Selectable( select => select.Mode( GridSelectionMode.Single ).Type( GridSelectionType.Row ) )
      .Reorderable( reorder => reorder.Columns( false ) )
     .Pageable(pager => pager.PageSizes(true).PageSizes(new int[] { 100,250,500,1000 }))
      .AutoBind( false )
      .Sortable( sortable => sortable.SortMode( GridSortMode.MultipleColumn ) )
      .Resizable( resize => resize.Columns( true ) )
      .Scrollable()
      .Events(events => events.DataBound("OnGridDataBound"))
      .Events(events => events.Change("OnRowSelected"))
         .Events(events => events.ColumnResize("OnRowResized"))
      .DataSource( dataSource => dataSource.Ajax().Read( read => read.Action( "GetConnectionEvents", "Events" ).Data("additionalData") )
      ))