Duncan.PEMS.Web/Areas/city/Controllers/WorkOrdersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Duncan.PEMS.Business.Assets;
using Duncan.PEMS.Business.Customers;
using Duncan.PEMS.Business.Exports;
using Duncan.PEMS.Business.Grids;
using Duncan.PEMS.Business.Resources;
using Duncan.PEMS.Business.Utility;
using Duncan.PEMS.Business.WebServices;
using Duncan.PEMS.Business.WorkOrders;
using Duncan.PEMS.Entities.Assets;
using Duncan.PEMS.Entities.Customers;
using Duncan.PEMS.Entities.Enumerations;
using Duncan.PEMS.Entities.WebServices.FieldMaintenance;
using Duncan.PEMS.Entities.WorkOrders;
using Duncan.PEMS.Entities.WorkOrders.Dispatcher;
using Duncan.PEMS.Framework.Controller;
using Duncan.PEMS.Utilities;
using Kendo.Mvc;
using Kendo.Mvc.UI;
using NLog;
using NPOI.HSSF.UserModel;
using iTextSharp.text;
using iTextSharp.text.pdf;

namespace Duncan.PEMS.Web.Areas.city.Controllers
{
     [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
    public class WorkOrdersController : PemsController
    {
        #region NLog Logger

        /// <summary>
        /// NLog logger instance.
        /// </summary>
        private static Logger _logger = LogManager.GetCurrentClassLogger();

        #endregion


        #region Listing
         public ActionResult Index()
         {
             ViewBag.CurrentCityID = CurrentCity.Id;
             return View();
         }

         [HttpGet]
         public ActionResult GetWorkOrders([DataSourceRequest] DataSourceRequest request, int alarmCode = -1)
         {
             //now save the sort filters
             if (request.Sorts.Count > 0)
                 SetSavedSortValues(request.Sorts, "WorkOrder");

             //get models
             var models = (new DispatcherWorkOrderFactory(CurrentCity)).GetWorkOrders(alarmCode);


             //sort, page, filter, group them
             var items = models.AsQueryable();
             items = items.ApplyFiltering(request.Filters);
             var total = items.Count();
             items = items.ApplySorting(request.Groups, request.Sorts);
             items = items.ApplyPaging(request.Page, request.PageSize);
             IEnumerable data = items.ToList();

             DataSourceResult result = new DataSourceResult()  //** Sairam made changes on dec 17th 2014
             //var result = new DataSourceResult
             {
                 Data = data,
                 Total = total
             };

             return Json(result, JsonRequestBehavior.AllowGet);
         }
       
        #endregion

        #region "Filter Values"
         /// <summary>
         /// Gets all of the possible asset tyeps for all customers in the current maintenance group
         /// </summary>
         /// <returns></returns>
         public JsonResult GetAssetTypes()
         {
             //get all of the unique asset types for each customer in the maintenance group
             //get the maintenance group
             var maintGroup = new PemsCity(Session[Constants.ViewData.CurrentCityId].ToString());
             var items = (new DispatcherWorkOrderFactory(maintGroup)).GetWorkOrderAssetTypes();
             return Json(items, JsonRequestBehavior.AllowGet);
         }

         /// <summary>
         /// Gets all of the possible assignment States for all customers in the current maintenance group
         /// </summary>
         /// <returns></returns>
         public JsonResult GetAssignmentStates()
         {
             //get all of the unique assignment states for each customer in the maintenance group
             //get the maintenance group
             var maintGroup = new PemsCity(Session[Constants.ViewData.CurrentCityId].ToString());
             var items = (new DispatcherWorkOrderFactory(maintGroup)).GetWorkOrderAssignmentStates();
             return Json(items, JsonRequestBehavior.AllowGet);
         }

         public JsonResult GetTechnicians()
         {
             //get all of the technicains for each customer in the maintenance group
             //get the maintenance group
             var maintGroup = new PemsCity(Session[Constants.ViewData.CurrentCityId].ToString());
             var items = (new DispatcherWorkOrderFactory(maintGroup)).GetWorkOrderTechnicians();
             return Json(items, JsonRequestBehavior.AllowGet);
         }

         /// <summary>
         /// Gets all the asset types int he systme
         /// </summary>
         /// <returns></returns>
        public JsonResult GetPartAssetTypes()
        {
            //get a unique list of meter groups in the system for all of the customers in a maintenance group.
            var items = (new DispatcherWorkOrderFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString(), Session[Constants.Security.MaintenanceConnectionStringSessionVariableName].ToString())).GetAllMeterGroups();
            return Json(items, JsonRequestBehavior.AllowGet);
        }
         /// <summary>
         /// Get all the asset sub-types (categories, or mechanism masters) in the system
         /// </summary>
         /// <returns></returns>
        public JsonResult GetPartCategories()
        {
            //get a unique list of meter groups in the system for all of the customers in a maintenance group.
            var items = (new DispatcherWorkOrderFactory(Session[Constants.Security.ConnectionStringSessionVariableName].ToString(), Session[Constants.Security.MaintenanceConnectionStringSessionVariableName].ToString())).GetAllMechanisms();
            return Json(items, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Work Order Exporting

        public FileResult ExportToCsv([DataSourceRequest]DataSourceRequest request, int alarmCode = -1)
        {
            var items = GetExportData(request, alarmCode);
            var output = (new ExportFactory()).GetCsvFileMemoryStream(items, CurrentController, "GetWorkOrders", CurrentCity.Id);
            return File(output, "text/comma-separated-values", "WorkOrdersExport_" + FormatHelper.FormatDateTime(DateTime.Now) + ".csv");
        }

        public FileResult ExportToExcel([DataSourceRequest]DataSourceRequest request, int alarmCode = -1)
        {
            var items = GetExportData(request, alarmCode);
            var filters = new List<FilterDescriptor>();
            //pass in an empty list
            filters = GetFilterDescriptors(request.Filters, filters);
            //we have to add alarm code
            if (alarmCode > -1)
                filters.Add(new FilterDescriptor { Member = "Alarm Code", Value = alarmCode.ToString() });

            var output = (new ExportFactory()).GetExcelFileMemoryStream(items, CurrentController, "GetWorkOrders", CurrentCity.Id, filters);
            return File(output.ToArray(),   //The binary data of the XLS file
              "application/vnd.ms-excel", //MIME type of Excel files
              "WorkOrdersExport_" + FormatHelper.FormatDateTime(DateTime.Now) + ".xls");     //Suggested file name in the "Save as" dialog which will be displayed to the end user
        }

        public FileResult ExportToPdf([DataSourceRequest]DataSourceRequest request, int alarmCode = -1)
        {
            var items = GetExportData(request, alarmCode);
            var filters = new List<FilterDescriptor>();
            //pass in an empty list
            filters = GetFilterDescriptors(request.Filters, filters);
            //we have to add alarm code
            if (alarmCode > -1)
                filters.Add(new FilterDescriptor { Member = "Alarm Code", Value = alarmCode.ToString() });
            var output = (new ExportFactory()).GetPDFFileMemoryStream(items, CurrentController, "GetWorkOrders", CurrentCity.Id, filters, 2);

            // send the memory stream as File
            return File(output.ToArray(), "application/pdf", "WorkOrdersExport_" + FormatHelper.FormatDateTime(DateTime.Now) + ".pdf");
        }

        private IEnumerable<DispatcherWorkOrderListModel> GetExportData(DataSourceRequest request, int alarmCode = -1)
        {
            //get models
            var models = (new DispatcherWorkOrderFactory(CurrentCity)).GetWorkOrders(alarmCode);

            //sort, page, filter, group them
            var items = models.AsQueryable();
            items = items.ApplyFiltering(request.Filters);
            var total = items.Count();
            items = items.ApplySorting(request.Groups, request.Sorts);
            items = items.ApplyPaging(request.Page, request.PageSize);
            return items.ToList();
        }

        #endregion

        #region "Parts Exporting"

        public FileResult ExportPartsToCsv([DataSourceRequest]DataSourceRequest request)
        {
            var items = GetPartsExportData(request);
            var gridData = (new GridFactory()).GetGridData(CurrentController, "GetAvailableParts", CurrentCity.Id);
            var output = new MemoryStream();
            var writer = new StreamWriter(output, Encoding.UTF8);
            AddCsvValue(writer, GetLocalizedGridTitle(gridData, "Part ID"));
            AddCsvValue(writer, GetLocalizedGridTitle(gridData, "Part Name"));
            AddCsvValue(writer, GetLocalizedGridTitle(gridData, "Asset Type"));
            AddCsvValue(writer, GetLocalizedGridTitle(gridData, "Category"));
            AddCsvValue(writer, GetLocalizedGridTitle(gridData, "Part Description"));
            AddCsvValue(writer, GetLocalizedGridTitle(gridData, "Retail Cost"));
            AddCsvValue(writer, GetLocalizedGridTitle(gridData, "Part Status"), true);
            foreach (AvailablePart item in items)
            {
                //add a item for each property here
                AddCsvValue(writer, item.PartId.ToString());
                AddCsvValue(writer, item.PartName);
                AddCsvValue(writer, item.MeterGroupDisplay);

Duncan.PEMS.Web/Areas/maint/Views/WorkOrders/CreateEvent.cshtml
@using Duncan.PEMS.Utilities
@using Kendo.Mvc.UI

@model Duncan.PEMS.Entities.WorkOrders.Technician.TechnicianCreateEventModel

@{
    ViewBag.Title = @HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Create Event" );
}
                     
@section PageHeader 
{
     <h2>@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Create Event" )</h2>
     <a class="back" href='/' >@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Back" )</a>

}

@using (Html.BeginForm("CreateEvent", "WorkOrders", FormMethod.Post, new { @id = "createForm" }))
{

<div id="content-inner">
           <div class="validationSum-container">@Html.HeaderMessage()</div>
    
    
    @if (Model.AssetIdOptions.Any())
    {
        <div class="two-column">
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "WO#"):</div>
            <div class="customer_text">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Generated")</div>
        </div>
        <div class="two-column">
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Event ID"):</div>
            <div class="customer_text">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Generated")</div>
        </div>
        <div class="clear">
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Asset ID (Area)"):</div><br/>
            @(Html.Kendo().ComboBoxFor(x => x.SelectedAssetKey)
                  .Filter("contains")
                  .HtmlAttributes(new {style = "width:100%"})
                  .SelectedIndex(0)
                  .Events(evt => evt.Change("asChange"))
                  .BindTo(new SelectList(Model.AssetIdOptions, "UniqueKey", "AssetIdFullDisplay"))
                  .Suggest(true)
                  )
        </div>
        <div class="clear">
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Fault Description"):</div><br/>
            @(Html.Kendo().ComboBoxFor(x => x.SelectedFaultDescription)
                  .Filter("contains")
                  .HtmlAttributes(new {style = "width:100%"})
                  .SelectedIndex(0)
                  .Events(evt => evt.Change("fdChange"))
                  .BindTo(new SelectList(Model.FaultDescriptions, "Value", "Text"))
                  .Suggest(true)
                  )
        
        </div>
        <div class="clear">
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Notes"):</div>
      
            @Html.TextAreaFor(m => m.Notes, new {@class = "customer_text_area long_text_area", rows = "5"})
        </div>
        <div class="clear" id="image-upload">
            <a class="button" id="get-images" href="#" onclick=" LoadFileUpload() "></a>
            <input name="files" id="files" type="file" /> 
        </div>
        <div class="clear button-row">
            <a class="button important" onclick=" Submit(); " href="#">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Save")</a>
        </div>
    }
    else
    {
        <div class="clear">
            Unable to create events: No Assets found.
        </div>
    }

</div>
    <script>
        function Submit() {
            
            //check the values
            if (!$("#SelectedAssetKey").data("kendoComboBox").value()) {
                alert('Select an asset');
            }
            else if (!$("#SelectedFaultDescription").data("kendoComboBox").value()) {
                alert('Select an Fault');

            } else {
                $('#createForm').submit();

            }
        }
        
        function LoadFileUpload() {
            $("#files").click();
        }
      
        function fdChange(e) {
            if (this.selectedIndex == -1) {
                var dt = this.dataSource._data[0];
                this.text(dt[this.options.dataTextField]);
                this._selectItem();
            }
        }
        
        function asChange(e) {
            if (this.selectedIndex == -1) {
                var dt = this.dataSource._data[0];
                this.text(dt[this.options.dataTextField]);
                this._selectItem();
            }
        }

        $(document).ready(function () {
            $("#files").kendoUpload({
                select: onSelect,
                remove: onRemove
            });
        });

        var totalFiles = 0;
        var onSelect = function (e) {
            var selectedFiles = e.files.length;
            //only 3 per work order
            if (totalFiles + selectedFiles > 3) {
                alert("3 images allowed");
                e.preventDefault();
            }
            else {
                totalFiles += selectedFiles;
            }

            $.each(e.files, function (index, value) {
                var extension = value.extension.trim().toLowerCase();
                //only images
                if (extension != ".png"
                    && extension != ".jpeg"
                    && extension != ".jpg") {
                    e.preventDefault();
                    alert("Image Files Only");
                }
            });
        };

        function onRemove(e) {
            totalFiles--;
        }

    </script>
    <style>
        .k-upload-button {
            visibility: hidden;
        }
    </style>
}

Duncan.PEMS.Web/Areas/maint/Views/WorkOrders/EventDetails.cshtml
@using Duncan.PEMS.Utilities
@using Kendo.Mvc.UI
@model Duncan.PEMS.Entities.WorkOrders.Technician.TechnicianEventDetailsModel


@{
    ViewBag.Title = @HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Event Details" );
}
                     
@section PageHeader 
{
      <h2>@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Event Detail" ) </h2>
      <a class="back" href='@Url.Action("WorkOrderDetails", "WorkOrders", new { workOrderId = @Model.WorkOrderEvent.WorkOrderId, selectedSort =ViewBag.SortOrder, sortDirection = ViewBag.SortDirection })' >@HttpContext.Current.GetLocaleResource( ResourceTypes.Glossary, "Back" )</a>
}

@section Scripts 
{
}

<style>
           .k-window { width: 100%;}
            .k-overlay {
            z-index: 20000;
            cursor: pointer;
        }
</style>

<div id="content-inner">
    <div class="clear">
        <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "WO#"):</div>
        <div class="customer_text">@Model.WorkOrderEvent.WorkOrderId</div>
    </div>
    <div class="clear">
        <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Asset ID"):</div>
        <div class="customer_text">@Model.WorkOrderAsset.AssetId</div>
    </div>
    <div class="clear">
        <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Asset Type"):</div>
        <div class="customer_text">@Model.WorkOrderAsset.AssetType</div>
    </div>
    <div class="clear">
        <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Asset Subtype"):</div>
        <div class="customer_text">@Model.WorkOrderAsset.AssetSubType</div>
    </div>
    <div class="clear">
        <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Source"):</div>
        <div class="customer_text">@Model.Source</div>
    </div>
    <div class="clear">
        <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Alarm Code"):</div>
        <div class="customer_text">@Model.WorkOrderEvent.EventCode</div>
    </div>
    <div class="clear">
        <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Description"):</div>
        <div class="customer_text">@Model.WorkOrderEvent.EventDesc</div>
    </div>
    <div class="clear">
        <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Severity"):</div>
        <div class="customer_text">@Model.WorkOrderEvent.SeverityDisplay</div>
    </div>
    <div class="clear">
        <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Deadline"):</div>
        <div class="customer_text">@Model.WorkOrderEvent.SLADueDisplay</div>
    </div>
    <div class="clear">
        <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Fault Reported Notes"):</div>
        <div class="customer_text">@Model.WorkOrderEvent.Notes</div>
    </div>
    <div class="clear" id="image-upload">
         @HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Attached Images"):<br />
            @{
                if (Model.WorkOrderImages.Any())
                {
                    foreach (var workOrderImage in Model.WorkOrderImages)
                    {
                        @(Html.Kendo().Window()
                              .Name("workOrderImage" + @workOrderImage.WorkOrderImageId)
                              .Title("Image: " + @workOrderImage.ImageName)
                              .Actions(actions => actions
                                                      .Close())
                              .Content(@<text>
                                             <img alt="" style="max-width: 100%" src="@workOrderImage.ImageSource"/>
                                        </text>)
                              .Draggable(false)
                              .Resizable(res => res.Enabled(false))
                              .Modal(true)
                              .Visible(false)

                              )
                        <a href="#" id='open_@workOrderImage.WorkOrderImageId' >WO# @workOrderImage.ImageName</a><br/>

                        <script>
                            $(document).ready(function() {
                                var dialog = $("#workOrderImage" + @workOrderImage.WorkOrderImageId);
                               
                                $("#open_" + @workOrderImage.WorkOrderImageId).bind("click", function() {
                                    dialog.data("kendoWindow").open();
                                    dialog.data("kendoWindow").center();
                                });
                            });
                            
                            $(document).on('click', ".k-overlay" , function() {
                                var dialog = $("#workOrderImage" + @workOrderImage.WorkOrderImageId);
                                   dialog.data("kendoWindow").close();
                               });
                        </script>
                    }
                }
                else
                {
                    @HttpContext.Current.GetLocaleResource(ResourceTypes.Glossary, "None")
                }
            }
    </div>
</div>

Duncan.PEMS.Web/Areas/maint/Views/WorkOrders/Images.cshtml
@using Duncan.PEMS.Utilities
@using Kendo.Mvc.UI
@model Duncan.PEMS.Entities.WorkOrders.Technician.TechnicianWorkOrderDetailsModel

@{
    ViewBag.Title = @HttpContext.Current.GetLocaleResource( ResourceTypes.PageTitle, "Work Order Images" );
}
                     
@section PageHeader 
{
    <h2>@HttpContext.Current.GetLocaleResource(ResourceTypes.Glossary, "Work Order Images") </h2>
   <a class="back" href='@Url.Action("ResolveWorkOrder", "WorkOrders", new { workOrderId = @Model.WorkOrderId, selectedSort = ViewBag.SortOrder, sortDirection = ViewBag.SortDirection })' >@HttpContext.Current.GetLocaleResource(ResourceTypes.Glossary, "Back")</a>
}

@section Scripts 
{
}

@using (Html.BeginForm("Images", "WorkOrders", FormMethod.Post, new { @id = "imageForm" }))
{
    <input type="hidden" value="@ViewBag.SortOrder" name="selectedSort"/>
    <input type="hidden" value="@ViewBag.SortDirection" name="sortDirection"/>
    <input type="hidden" value="@Model.WorkOrderId" name="workOrderId"/>
    <div id="content-inner">
        <div class="validationSum-container">@Html.HeaderMessage()</div>
        <div   class="clear">
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "WO#"):</div>
            <div class="customer_text">@Model.WorkOrderId</div>
        </div>
        <div class="clear">
            <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Do you have images to attach?"):</div>
        </div>
           <div class="clear" id="image-upload">
            <a class="button" id="get-images" href="#" onclick="LoadFileUpload()"></a>
            <input name="files" id="files" type="file" />

            @HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Attached Images"):<br />
            @{
                if (Model.WorkOrderImages.Any())
                {
                    foreach (var workOrderImage in Model.WorkOrderImages)
                    {
                        @(Html.Kendo().Window()
                              .Name("workOrderImage" + @workOrderImage.WorkOrderImageId)
                              .Title("Image: " + @workOrderImage.ImageName)
                              .Actions(actions => actions
                                                      .Close())
                              .Content(@<text>
                                             <img alt="" style="max-width: 100%" src="@workOrderImage.ImageSource"/>
                                        </text>)
                              .Draggable(false)
                              .Resizable(res => res.Enabled(false))
                              .Modal(true)
                              .Visible(false)

                              )
                        <a href="#" id='open_@workOrderImage.WorkOrderImageId' >WO# @workOrderImage.ImageName</a><br/>

                        <script>
                            $(document).ready(function() {
                                var dialog = $("#workOrderImage" + @workOrderImage.WorkOrderImageId);
                               
                                $("#open_" + @workOrderImage.WorkOrderImageId).bind("click", function() {
                                    dialog.data("kendoWindow").open();
                                    dialog.data("kendoWindow").center();
                                });
                            });
                            $(document).on('click', ".k-overlay" , function() {
                                var dialog = $("#workOrderImage" + @workOrderImage.WorkOrderImageId);
                                dialog.data("kendoWindow").close();
                            });
                        </script>
                    }
                }
                else
                {
                    @HttpContext.Current.GetLocaleResource(ResourceTypes.Glossary, "None")
                }
            }
        </div>
        <div class="clear button-row">
              <a class="button important" onclick="Submit('Save');" href="#">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Update")</a>
        </div>
    </div>

    <script>

        $(document).ready(function() {
            $("#files").kendoUpload({
                select: onSelect,
                remove: onRemove
            });
        });

        function LoadFileUpload() {
            $("#files").click();
        }

        var totalFiles = @Model.WorkOrderImages.Count();
        var onSelect = function(e) {
            var selectedFiles = e.files.length;
            //only 3 per work order
            if (totalFiles + selectedFiles > 3) {
                alert("3 images allowed");
                e.preventDefault();
            } else {
                totalFiles += selectedFiles;
            }

            $.each(e.files, function(index, value) {
                var extension = value.extension.trim().toLowerCase();
                //only images
                if (extension != ".png"
                    && extension != ".jpeg"
                    && extension != ".jpg") {
                    e.preventDefault();
                    alert("Image Files Only");
                }
            });
        };

        function onRemove(e) {
            totalFiles--;
        }
        function Submit(btnValue) {
            $('<input />').attr('type', 'hidden').attr('name', 'submitButton').attr('value', btnValue).appendTo('#imageForm');
            $('#imageForm').submit();
        }
    </script>
        <style>
        .k-upload-button {
            visibility: hidden;
        }

           .k-window { width: 100%;}
        .k-overlay {
            z-index: 20000;
            cursor: pointer;
        }
    </style>
}

Duncan.PEMS.Web/Areas/maint/Views/WorkOrders/ResolveEvents.cshtml
@using Duncan.PEMS.Utilities
@model Duncan.PEMS.Entities.WorkOrders.Technician.TechnicianWorkOrderDetailsModel

@{
    ViewBag.Title = @HttpContext.Current.GetLocaleResource(ResourceTypes.PageTitle, "Resolve Multiple Alarms");
}
                     
@section PageHeader 
{
    <h2>@HttpContext.Current.GetLocaleResource(ResourceTypes.Glossary, "Work Order Event Detail")</h2>
     <a class="back" href='@Url.Action("WorkOrderDetails", "WorkOrders", new { workOrderId = @Model.WorkOrderId, selectedSort = ViewBag.SortOrder, sortDirection = ViewBag.SortDirection })' >@HttpContext.Current.GetLocaleResource(ResourceTypes.Glossary, "Back")</a>
}


@using (Html.BeginForm("GetResolveEvents", "WorkOrders", FormMethod.Get, new { @id = "eventForm" }))
{

<input type="hidden" value="@ViewBag.SortOrder" name="selectedSort"/>
<input type="hidden" value="@ViewBag.SortDirection" name="sortDirection"/>
<input type="hidden" value="@Model.WorkOrderId" name="workOrderId"/>


    <div id="content-inner">
           <div class="validationSum-container">@Html.HeaderMessage()</div>
        <div class="clear">
            <div class="two-column">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "WO#"):</div>
                <div class="customer_text">@Model.WorkOrderId</div>
            </div>
            <div class="two-column">
                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Asset ID"):</div>
                <div class="customer_text">@Model.WorkOrderAsset.AssetId</div>
            </div>
        </div>

        <div class="clear">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Select Events To Resolve"):</div>
      
      
        <div class="clear" id="event-detail">
            <table cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <td colspan="2" class="event-detail-header">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Event Detail")</td>
                </tr>
                @{

                    if (Model.WorkOrderEvents.Any())
                    {
                        bool even = false;
                        foreach (var workOrderEvent in Model.WorkOrderEvents)
                        {
                            string classname = even ? "even" : "";

                            <tr class="event-detail-row @classname">
                                <td>
                                    <div class="customer_text_label">@workOrderEvent.EventDesc - @workOrderEvent.EventCode - @workOrderEvent.StatusDisplay</div>
                                </td>
                                <td>
                                    <input name="eventIds" value="@workOrderEvent.WorkOrderEventId" class="checkbox" type="checkbox">
                                </td>
                            </tr>
                            even = !even;
                        }
                    }
                    else
                    {
                        <tr class="event-detail-row ">
                            <td>
                                <div class="customer_text_label">@HttpContext.Current.GetLocaleResource(ResourceTypes.Glossary, "None")</div>
                            </td>
                        </tr>
                    }

                }
            </table>
        </div>

        <div class="clear button-row">
            <a class="button important" onclick="Submit('Resolve');" href="#">@HttpContext.Current.GetLocaleResource(ResourceTypes.Label, "Resolve")</a>
        </div>
    </div>
    
    <script>
        function Submit(btnValue) {
            $('<input />').attr('type', 'hidden').attr('name', 'submitButton').attr('value', btnValue).appendTo('#eventForm');
            $('#eventForm').submit();
        }
    </script>
}
    